const TableData=[
    {
        id:"HD82NA2H",
        data:"2022-06-09",
        time:"07:06 PM",
        transactionType:"INR Deposit",
        transferType:"E-Transfer",
        amount:"+ ₹81,123.10",
        sumAmount:"",
        status:"pending",
        category:"deposit",
    },
    {
        id:"PD32NA2H",
        data:"2022-06-07",
        time:"02:48 PM",
        transactionType:"INR Withdraw",
        transferType:"Wire Transfer",
        amount:"- ₹81,123.10",
        sumAmount:"",
        status:"cancelled",
        category:"withdraw",
    },
    {
        id:"ACV32A13",
        data:"2022-06-04",
        time:"09:21 AM",
        transactionType:"Buy",
        transferType:"",
        amount:"+ 12.48513391 BTC",
        sumAmount:"- $81,123.10",
        status:"processing",
        category:"trade",
    },
    {
        id:"POH789RT",
        data:"2022-06-03",
        time:"01:32 PM",
        transactionType:"Sell",
        transferType:"",
        amount:"- 0.36401628 BTC",
        sumAmount:"+ $19,378.84",
        status:"completed",
        category:"trade",
    },
];

export default TableData;